version: "3"

services:
  WebServer:
    container_name: WebServer-Nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./content:/usr/share/nginx/html/
    
  MySQL:
    container_name: MySQL-Employees
    image: genschsa/mysql-employees 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
